MEALS = [
    {
        "id": 1,
        "tipo": "Desayuno",
        "fase": "blando",
        "nombre": "Huevo revuelto suave con queso fresco",
        "ingredientes": "1 huevo, 20 g de queso fresco, 1 cucharadita de aceite de oliva",
        "porcion": "Porción pequeña. Comer lento y en bocados chicos.",
        "proteina": 12,
        "kcal": 165,
        "vitaminas": "B12, D, calcio",
        "nota": "Priorizar proteína y detenerse si aparece saciedad."
    },
    {
        "id": 2,
        "tipo": "Desayuno",
        "fase": "regular",
        "nombre": "Yogur griego natural con frutilla",
        "ingredientes": "150 g de yogur griego natural sin azúcar, 3 frutillas picadas",
        "porcion": "Comer despacio. Evitar azúcar añadida.",
        "proteina": 15,
        "kcal": 130,
        "vitaminas": "Calcio, B12, vitamina C",
        "nota": "Buena opción fría, simple y fácil de preparar."
    },
    {
        "id": 3,
        "tipo": "Desayuno",
        "fase": "regular",
        "nombre": "Quesillo con palta pequeña",
        "ingredientes": "80 g de quesillo, 1/4 de palta pequeña",
        "porcion": "Porción chica. Comer lento y masticar bien.",
        "proteina": 13,
        "kcal": 180,
        "vitaminas": "Calcio, B12, vitamina E",
        "nota": "Usar poca palta para evitar exceso de grasa."
    },
    {
        "id": 4,
        "tipo": "Desayuno",
        "fase": "blando",
        "nombre": "Yogur natural con proteína",
        "ingredientes": "120 g de yogur natural sin azúcar, 1/2 medida de proteína indicada por nutricionista",
        "porcion": "Textura suave. Consumir lentamente.",
        "proteina": 18,
        "kcal": 150,
        "vitaminas": "Calcio, B12",
        "nota": "Usar proteína solo si fue autorizada por el equipo médico."
    },
    {
        "id": 5,
        "tipo": "Desayuno",
        "fase": "regular",
        "nombre": "Omelette simple de queso fresco",
        "ingredientes": "1 huevo, 25 g de queso fresco, un poco de ciboulette si tolera",
        "porcion": "Porción pequeña. Evitar pan si no está indicado.",
        "proteina": 14,
        "kcal": 175,
        "vitaminas": "B12, D, calcio",
        "nota": "Preparar sin mantequilla y con poco aceite."
    },
    {
        "id": 6,
        "tipo": "Desayuno",
        "fase": "blando",
        "nombre": "Ricotta o quesillo molido",
        "ingredientes": "90 g de ricotta baja en grasa o quesillo molido",
        "porcion": "Textura blanda. Comer lento.",
        "proteina": 12,
        "kcal": 140,
        "vitaminas": "Calcio, B12",
        "nota": "Buena alternativa si no tolera huevo."
    },
    {
        "id": 7,
        "tipo": "Desayuno",
        "fase": "regular",
        "nombre": "Jamón de pavo con quesillo",
        "ingredientes": "2 láminas de jamón de pavo bajo en sodio, 60 g de quesillo",
        "porcion": "Porción pequeña. Masticar bien.",
        "proteina": 16,
        "kcal": 150,
        "vitaminas": "B12, calcio",
        "nota": "Elegir versiones bajas en sodio."
    },
    {
        "id": 8,
        "tipo": "Desayuno",
        "fase": "regular",
        "nombre": "Yogur con plátano pequeño",
        "ingredientes": "120 g de yogur natural sin azúcar, 1/3 de plátano pequeño",
        "porcion": "Comer lento. No agregar azúcar.",
        "proteina": 10,
        "kcal": 145,
        "vitaminas": "Calcio, potasio, B12",
        "nota": "Usar poca fruta para evitar exceso de azúcar."
    },

    {
        "id": 9,
        "tipo": "Almuerzo",
        "fase": "blando",
        "nombre": "Pollo desmenuzado con puré de zapallo",
        "ingredientes": "70 g de pollo cocido desmenuzado, 1/2 taza de puré de zapallo, caldo bajo en sodio",
        "porcion": "Textura húmeda. Masticar muy bien.",
        "proteina": 22,
        "kcal": 210,
        "vitaminas": "B6, vitamina A, hierro",
        "nota": "Humedecer con caldo para mejor tolerancia."
    },
    {
        "id": 10,
        "tipo": "Almuerzo",
        "fase": "regular",
        "nombre": "Pescado al horno con verduras cocidas",
        "ingredientes": "80 g de merluza o reineta, zanahoria y zapallito italiano cocidos",
        "porcion": "Comer primero la proteína y luego las verduras.",
        "proteina": 21,
        "kcal": 190,
        "vitaminas": "D, B12, omega 3",
        "nota": "Evitar frituras y salsas pesadas."
    },
    {
        "id": 11,
        "tipo": "Almuerzo",
        "fase": "regular",
        "nombre": "Pavo molido con verduras cocidas",
        "ingredientes": "70 g de pavo molido cocido, zanahoria cocida, zapallo italiano cocido",
        "porcion": "Porción chica. Comer en 20 a 30 minutos.",
        "proteina": 20,
        "kcal": 210,
        "vitaminas": "B3, B6, vitamina A",
        "nota": "Evitar condimentos fuertes si todavía hay sensibilidad."
    },
    {
        "id": 12,
        "tipo": "Almuerzo",
        "fase": "blando",
        "nombre": "Carne molida magra con puré de verduras",
        "ingredientes": "60 g de carne molida magra, puré de zanahoria o zapallo",
        "porcion": "Porción pequeña. Textura blanda.",
        "proteina": 18,
        "kcal": 220,
        "vitaminas": "Hierro, B12, zinc",
        "nota": "Elegir carne magra y evitar grasa visible."
    },
    {
        "id": 13,
        "tipo": "Almuerzo",
        "fase": "regular",
        "nombre": "Tortilla simple de atún",
        "ingredientes": "1 huevo, 1/2 lata de atún al agua, verduras cocidas picadas",
        "porcion": "Porción pequeña. Comer lento.",
        "proteina": 24,
        "kcal": 230,
        "vitaminas": "B12, D, hierro",
        "nota": "Escurrir bien el atún y evitar mayonesa."
    },
    {
        "id": 14,
        "tipo": "Almuerzo",
        "fase": "regular",
        "nombre": "Pollo cocido con ensalada blanda",
        "ingredientes": "80 g de pollo cocido, betarraga cocida o zanahoria cocida",
        "porcion": "Proteína primero. Verduras después.",
        "proteina": 24,
        "kcal": 200,
        "vitaminas": "B6, vitamina A, hierro",
        "nota": "Evitar ensaladas crudas si todavía no las tolera."
    },
    {
        "id": 15,
        "tipo": "Almuerzo",
        "fase": "regular",
        "nombre": "Huevo duro con pollo picado",
        "ingredientes": "1 huevo duro, 50 g de pollo picado fino, verduras cocidas",
        "porcion": "Porción pequeña. Masticar mucho.",
        "proteina": 20,
        "kcal": 220,
        "vitaminas": "B12, D, B6",
        "nota": "Ideal si tolera bien el huevo."
    },
    {
        "id": 16,
        "tipo": "Almuerzo",
        "fase": "blando",
        "nombre": "Puré de lentejas con pollo",
        "ingredientes": "1/3 taza de lentejas cocidas molidas, 50 g de pollo desmenuzado",
        "porcion": "Textura suave. Porción pequeña.",
        "proteina": 18,
        "kcal": 240,
        "vitaminas": "Hierro, folato, B6",
        "nota": "Usar solo si tolera legumbres. Evitar aliños fuertes."
    },
    {
        "id": 17,
        "tipo": "Almuerzo",
        "fase": "regular",
        "nombre": "Jurel al natural con verduras cocidas",
        "ingredientes": "70 g de jurel al natural, zanahoria cocida, zapallito italiano",
        "porcion": "Comer lento y revisar tolerancia.",
        "proteina": 19,
        "kcal": 210,
        "vitaminas": "Omega 3, D, B12",
        "nota": "Escurrir bien y evitar agregar mayonesa."
    },
    {
        "id": 18,
        "tipo": "Almuerzo",
        "fase": "regular",
        "nombre": "Ricotta con pollo y verduras",
        "ingredientes": "60 g de ricotta baja en grasa, 60 g de pollo cocido, verduras blandas",
        "porcion": "Porción pequeña.",
        "proteina": 22,
        "kcal": 230,
        "vitaminas": "Calcio, B12, B6",
        "nota": "Opción suave y alta en proteína."
    }
]